baseURL = 'https://zalepik.netlify.app/'
languageCode = 'en-us'
title = 'Zalepik Studio | Software House di Jombang Jawa Timur'
# Novela settings
theme = "zalepik"
summaryLength = 10
paginate = 15
[params]
    Description = "Studio Kami Memproduksi Website & Aplikasi. Melayani kebutuhan terkait website, aplikasi, desain, digital marketing dan lainnya. Temukan promo menarik melalui instagram kami!"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[[redirects]]
    from   = "/**"
    to     = "/404.html"
    status = 404

# paginate = 6

# [social]
# twitter= "https://twitter.com/forestryio"
# github= "https://github.com/forestryio/novela-hugo-starter"
# linkedin= "https://www.linkedin.com/company/forestry.io"
# instagram = "#"
# dribbble = "#"
# youtube = "#"

# [taxonomies]
# author = "authors"

# googleAnalytics = 'G-XHMEH4HT62'